/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UIPayload =
  | QuickReplies
  | Menu
  | DoctorCards
  | SlotButtons
  | AppointmentButtons
  | ConfirmationCard
  | HandoffCard;
export type Type = "quick_replies";
/**
 * @maxItems 3
 */
export type Options = [] | [string] | [string, string] | [string, string, string];
export type Type1 = "menu";
/**
 * @maxItems 4
 */
export type Options1 =
  | []
  | [MenuOption]
  | [MenuOption, MenuOption]
  | [MenuOption, MenuOption, MenuOption]
  | [MenuOption, MenuOption, MenuOption, MenuOption];
export type Label = string;
export type Text = string;
export type Type2 = "doctor_cards";
export type Name = string;
export type Specialty = string;
export type Days = string;
export type Hours = string;
export type Text1 = string;
export type Doctors = DoctorCard[];
export type Type3 = "slot_buttons";
export type DateLabel = string;
export type Doctor = string;
export type Label1 = string;
export type Text2 = string;
export type Slots = SlotChip[];
export type Groups = SlotGroup[];
export type Type4 = "appointment_buttons";
export type Label2 = string;
export type Text3 = string;
export type Appointments = AppointmentChip[];
export type Type5 = "confirmation_card";
export type Doctor1 = string;
export type Specialty1 = string;
export type Date = string;
export type Time = string;
export type VisitType = string;
export type AppointmentRef = string;
export type Type6 = "handoff_card";
export type DeskNumber = string;
export type TicketId = string | null;

export interface QuickReplies {
  type: Type;
  options: Options;
}
/**
 * Stacked full-width options under the greeting.
 */
export interface Menu {
  type: Type1;
  options: Options1;
}
export interface MenuOption {
  label: Label;
  text: Text;
}
export interface DoctorCards {
  type: Type2;
  doctors: Doctors;
}
export interface DoctorCard {
  name: Name;
  specialty: Specialty;
  days: Days;
  hours: Hours;
  text: Text1;
}
export interface SlotButtons {
  type: Type3;
  groups: Groups;
}
export interface SlotGroup {
  date_label: DateLabel;
  doctor: Doctor;
  slots: Slots;
}
export interface SlotChip {
  label: Label1;
  text: Text2;
}
export interface AppointmentButtons {
  type: Type4;
  appointments: Appointments;
}
export interface AppointmentChip {
  label: Label2;
  text: Text3;
}
export interface ConfirmationCard {
  type: Type5;
  doctor: Doctor1;
  specialty: Specialty1;
  date: Date;
  time: Time;
  visit_type: VisitType;
  appointment_ref: AppointmentRef;
}
export interface HandoffCard {
  type: Type6;
  desk_number: DeskNumber;
  ticket_id?: TicketId;
}
